### ISSUE TITLE
Versioning seems to be inaccurate.

### ISSUE THREAD

**Issue by brendanprice2003** [IntRevise/development-tracker#12]
The current versioning that is being used for this application, shown in the Readme.md, states that this application is in "Pre-Beta" but somehow still qualifies as a `1.0.8` version release, which by many standards is a version that is more than enough ready to be released. 

Review over the versioning scheme and perhaps implement semantic versioning via: https://github.com/semantic-release/semantic-release

I suggest that this application is currently at `0.1.3_beta`, based on this repo's commits and code changes per commit. 

For example:
`v2.3.6` / `major.minor.patch`

The major version is `2`. 
The minor version is `3`.
The patch version is `6`.

Use major to display the status of the application as a whole.
Use minor to display the progress to the next major version.
Use patch to display small amounts of code that fixed bugs or enhanced 'things'.

Having an accurate version number(s) means that the audience, yourself (as a programmer), and any other developers that would potentially be contributing, will be able to recognize what state the application is currently in. This may seem pointless right now in the early stages, (but trust me) it serves to be extremely useful when you come out of beta and require a (better) way to organize versions.

**Comment by axtonprice** [comment]
I've reviewed your suggestion and have removed the `Pre-Beta` tag on the repo.
The version `1.0.8` was synced with the IntRevise site version. Each backup created within the administration portal of the site creates a new version, which is where `v1.0.8` came from.

However, I understand the confusion this may have started. Seeing as versioning is not currently required for this stage in development (as at the moment, versioning is purely for the use of the lead developers of the project), we will refrain from using versioning on this tracker until at least we have a semi-stable & functioning site.
At that point, community-driven development will begin, where potential contributors will be able to view the progress of the project, as well as see current and past versions with patch/release notes.

Thank you
